apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- namespace.yaml
- rolebinding.yaml
- route.yaml
- service.yaml
- serviceaccount.yaml

images:
- name: ckcp
  newName: ghcr.io/kcp-dev/kcp
  newTag: ea614c0

namespace: ckcp
