---
resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - service.yaml
  - allow-argocd.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
