---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "github.com/openshift-pipelines/pipeline-service/operator/gitops/argocd/pipeline-service/pipelines-as-code?ref=main"
