---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tekton-results
resources:
  - https://github.com/openshift-pipelines/tektoncd-results.git/config/overlays/default-local-db/?ref=d384e7fec22bcd1b2c3e108a68cb32da4d4e6020
  - namespace.yaml
  - api-route.yaml
  - watcher-logging-rbac.yaml

images:
  - name: ko://github.com/tektoncd/results/cmd/api
    newName: docker.io/aandrienko/api:latest
    newTag: latest
  - name: ko://github.com/tektoncd/results/cmd/watcher
    newName: quay.io/redhat-appstudio/tekton-results-watcher
    newTag: d384e7fec22bcd1b2c3e108a68cb32da4d4e6020
  - name: ko://github.com/tektoncd/results/tools/migrator
    newName: quay.io/redhat-appstudio/tekton-results-migrator
    newTag: d384e7fec22bcd1b2c3e108a68cb32da4d4e6020

# generate a new configmap with updated values (logs api, db ssl mode) and replace the default one
configMapGenerator:
  - behavior: replace
    files:
      - env/config
    name: api-config
    namespace: tekton-pipelines
    options:
      disableNameSuffixHash: true

patches:
  - path: api-db-config.yaml
  - path: api-migrator-config.yaml
  - path: api-s3-config.yaml
  - path: api-sync.yaml
  - path: api-service-sync.yaml
  - path: api-service-tls.yaml
  - path: watcher-config.yaml
  - path: watcher-logging.yaml
  - path: watcher-sync.yaml
  - path: watcher-service-sync.yaml
  - path: delete-postgres-configmap.yaml
  - path: delete-postgres-service.yaml
  - path: delete-postgres-statefulset.yaml
