---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - permissions.yaml
  - service-account.yaml
  - configmap.yaml
  - route.yaml
  - deployment.yaml
  - service.yaml
  - db-service.yaml
  - db-configmap.yaml
  - db-statefulset.yaml
images:
  - name: tekton-results-api
    newName: quay.io/redhat-appstudio/tekton-results-api
    newTag: 18f7ee98d3f95d58d061a6ccee18fbfffeeae8f7
  - name: tekton-results-watcher
    newName: quay.io/redhat-appstudio/tekton-results-watcher
    newTag: 18f7ee98d3f95d58d061a6ccee18fbfffeeae8f7

patchesJson6902:
  - target:
      kind: Namespace
      name: tekton-results
    patch: |-
      - op: add
        path: "/metadata/labels"
        value:
          argocd.argoproj.io/managed-by: openshift-gitops

# generatorOptions:
#   disableNameSuffixHash: true

configMapGenerator:
  - name: tekton-results-config
    namespace: tekton-results
    files:
      - config
    literals:
      - foo=bar
      - DB_USER=
      - DB_PASSWORD=
      - DB_HOST=
      - DB_PORT=5432
      - DB_NAME=
      - DB_SSLMODE=disable
      - GRPC_PORT=50051
      - REST_PORT=8080
      - PROMETHEUS_PORT=9090
      - TLS_HOSTNAME_OVERRIDE=
      - TLS_PATH=/etc/tls
      - LOG_TYPE=File
      - LOG_CHUNK_SIZE=32768
      - LOGS_DATA=
      - S3_BUCKET_NAME=
      - S3_ENDPOINT=
      - S3_HOSTNAME_IMMUTABLE=false
      - S3_REGION=
      - S3_ACCESS_KEY_ID=
      - S3_SECRET_ACCESS_KEY=
      - S3_MULTI_PART_SIZE=5242880
generatorOptions:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  disableNameSuffixHash: true
