---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-results-api
  namespace: tekton-results
spec:
  template:
    spec:
      containers:
        - name: api
          env:
            # Enable logs api
            - name: LOGS_API
              value: "true"
            # Set up log type "S3"
            - name: LOG_TYPE
              value: S3
            # Set up S3 bucket name, where will be stored logs
            - name: S3_BUCKET_NAME
              value: tekton-results
            # Set up Minio tenant endpoint url
            - name: S3_ENDPOINT
              value: https://minio.tekton-results.svc.cluster.local
            # Set up S3 endpoint host name without bucket prefix
            - name: S3_HOSTNAME_IMMUTABLE
              value: "true"
            # Set up S3 region
            - name: S3_REGION
              value: us-east-1
