# TODO: [minio] move configuration for Minio to a patch in developer.
# Minio only appears when the deployment operated by "developer"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minio-admin
  annotations:
    argocd.argoproj.io/hook: PreSync
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - events
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - "*"
  - apiGroups:
      - minio.min.io
    resources:
      - tenants
    verbs:
      - "get"
      - "create"
      - "update"
  - apiGroups:
      - operators.coreos.com
    resources:
      - subscriptions
    verbs:
      - "get"
      - "create"
      - "update"
