---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "github.com/AndrienkoAleksandr/pipeline-service/operator/gitops/argocd/pipeline-service/tekton-chains?ref=dev-kustomization-3"
