---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/deployments

patchesStrategicMerge:
  - minio-tls-patch.yaml
  - minio-user-cred-patch.yaml
  - s3-configuration-patch.yaml
