---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patchesJson6902:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: tekton-results-api
      namespace: tekton-results
    path: tekton-results-api-patch.yaml
