---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "github.com/openshift-pipelines/AndrienkoAleksandr/operator/gitops/argocd/pipeline-service/tekton-results/base?ref=dev-kustomization-3"

patchesStrategicMerge:
  - minio-tls-patch.yaml
  - minio-user-cred-patch.yaml
  - s3-configuration-patch.yaml
