apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- pvc.yaml
- certs.yaml
- service.yaml
- route.yaml
- rolebinding.yaml
- serviceaccount.yaml
- deployment.yaml

patches:
  - target:
      kind: Route
      name: ckcp
      labelSelector: app=kcp-in-a-pod
    patch: |-
      - op: replace
        path: /spec/host
        description: Make sure you can use the route with your cluster or change accordingly if not.
        value: ckcp-ckcp.apps.ci-ln-6f8vpr2-72292.origin-ci-int-gce.dev.rhcloud.com
  # - target:
  #     kind: Deployment
  #     name: ckcp
  #     labelSelector: app=kcp-in-a-pod
  #   patch: |-
  #     - op: replace
  #       path: /spec/template/spec/containers/0/env/0/value
  #       description: This value refers to the hostAddress defined above.
  #       value: kcp.dev
  - target:
      kind: Certificate
      name: kcp
    patch: |-
      - op: add
        path: /spec/dnsNames/-
        description: This value refers to the hostAddress defined above.
        value: "*.apps.ci-ln-6f8vpr2-72292.origin-ci-int-gce.dev.rhcloud.com"

namespace: ckcp

images:
- name: kcp
  newName: ghcr.io/kcp-dev/kcp
  newTag: 50e3ab2
